### ISSUE TITLE
Curiosity: Want to know how its working

### ISSUE THREAD

**Issue by sboy99** [rubenjgarcia/nestjs-abac-app#1]
Hey @rubenjgarcia I'm Sagar very beginner in nestjs and starting my journey as a backend eng. Although I know the basic authorization technique such as RBAC but want to know advanced authorization like this. Would you please explain how it's working?

**Comment by rubenjgarcia** [comment]
I think this page can give you some understanding of what is ABAC and the comparison against RBAC

https://www.okta.com/identity-101/role-based-access-control-vs-attribute-based-access-control

**Comment by rubenjgarcia** [comment]
Close because it's not a bug

**Comment by sboy99** [comment]
Can you share resourceses to implement RBAC with persisted db?
